Repository mietechnologies/MIE-MCServer, pull requests merged in 2021-12, with the labels that each got.

#1 Added local backup capabilities
  main.py
  util/backup.py
  util/configuration.py
  util/date.py
Labels: enhancement

#7 Implemented Automagic Maintenance
  .gitignore
  clean-commands.txt
  config.yml
  end-regions.txt
  main.py
  util/configuration.py
Labels: enhancement

#11 RCON Refinements
  main.py
  util/configuration.py
  util/cron.py
  util/extension.py
Labels: enhancement

#18 Added first version of PR and PR review templates
  .github/PULL_REQUEST_REVIEW_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation

#20 Added CPU temperature monitoring if project is running on Raspberry Pi
  CHANGELOG.md
  main.py
  util/configuration.py
  util/cron.py
  util/temp.py
Labels: enhancement

#35 Mc/crontab username
  CHANGELOG.md
  main.py
  util/cron.py
  util/mielib/system.py
Labels: bug, enhancement

#37 Hidden password entry
  CHANGELOG.md
  util/configuration.py
  util/mielib/custominput.py
Labels: enhancement

#42 Temperature Monitor Fixes
  CHANGELOG.md
  main.py
  util/configuration.py
Labels: bug

#40 Bc/email error
  CHANGELOG.md
  main.py
  util/cron.py
  util/emailer.py
  util/mielib/system.py
  util/syslog.py
Labels: bug
