Repository mietechnologies/MIE-MCServer, pull requests merged in 2022-01, with the labels that each got.

#39 Command Terminal
  CHANGELOG.md
  command.py
  main.py
  minecraft/version.py
Labels: enhancement

#46 Fixes for end trimming
  CHANGELOG.md
  main.py
Labels: bug, enhancement

#36 Discord Integration
  CHANGELOG.md
  util/configuration.py
  util/mielib/custominput.py
  util/syslog.py
Labels: enhancement

#43 Custom Script File
  CHANGELOG.md
  main.py
  scripts/custom-command.sh
Labels: enhancement

#52 Updated Reboot Process
  CHANGELOG.md
  main.py
Labels: enhancement

#53 Password Encryption
  CHANGELOG.md
  main.py
  util/configuration.py
  util/emailer.py
Labels: enhancement, breaking
